### ISSUE TITLE
Viewer App is Not Rendering data for RBK

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/chaise#448]
The viewer app has an Angular error in the console. 
```
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module chaise.viewer due to:
TypeError: Cannot read property 'get' of undefined
    at configureUser (https://dev.rebuildingakidney.org/chaise/viewer/viewer.app.js?v=2ccabf22d99afbafecbdd2f655a322b6:59:23)
    at Object.invoke (https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:4665:19)
    at runInvokeQueue (https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:4558:35)
    at https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:4567:11
    at forEach (https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:322:20)
    at loadModules (https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:4548:5)
    at createInjector (https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:4470:19)
    at doBootstrap (https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:1746:20)
    at bootstrap (https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:1767:12)
    at angularInit (https://dev.rebuildingakidney.org/chaise/scripts/vendor/angular.js:1652:5)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=chaise.viewer&p1=Ty….rebuildingakidney.org%2Fchaise%2Fscripts%2Fvendor%2Fangular.js%3A1652%3A5)
```

Visit this url [https://dev.rebuildingakidney.org/chaise/viewer/#1/rbk:image/id=55](https://dev.rebuildingakidney.org/chaise/viewer/#1/rbk:image/id=55).

Here's the screenshot of the page.

![rbk](https://cloud.githubusercontent.com/assets/1658152/16051526/0aab35d6-3215-11e6-8aa9-d9616caa8d31.png)

**Comment by howdyjessie** [comment]
@chiragsanghvi The fix has been pushed to `master`. If you visit [the link you provided](https://dev.rebuildingakidney.org/chaise/viewer/#1/rbk:image/id=55), Viewer should be rendering data now.

**Comment by chiragsanghvi** [comment]
This is working now. Thanks.
