### ISSUE TITLE
Record page doesn't load in IE11

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#490]
Spun up a VM testing IE11 on Windows 7 - which is so far the most used flavor of IE visiting our sites and the version of chaise on dev.isrd.isi.edu has a serious bug that doesn't load the record page at all - it just displays the spinner. The error in the console reads:

TypeError: Object doesn't support property or method 'endsWith'
   at Anonymous function (https://data.gpcrconsortium.org/chaise/record/assets/javascripts/app.js?v=fd00039d6464ae44ead0dccb82436268:135:17)
   at Anonymous function (https://data.gpcrconsortium.org/chaise/scripts/vendor/angular.js:11255:13)
   at processQueue (https://data.gpcrconsortium.org/chaise/scripts/vendor/angular.js:15961:11)
   at Anonymous function (https://data.gpcrconsortium.org/chaise/scripts/vendor/angular.js:15977:27)
   at Scope.prototype.$eval (https://data.gpcrconsortium.org/chaise/scripts/vendor/angular.js:17229:9)
   at Scope.prototype.$digest (https://data.gpcrconsortium.org/chaise/scripts/vendor/angular.js:17045:15)
   at Scope.prototype.$apply (https://data.gpcrconsortium.org/chaise/scripts/vendor/angular.js:17337:13)
   at done (https://data.gpcrconsortium.org/chaise/scripts/vendor/angular.js:11572:36)
   at completeRequest (https://data.gpcrconsortium.org/chaise/scripts/vendor/angular.js:11778:7)
   at requestLoaded (htt

**Comment by hongsudt** [comment]
@crisaless please review.

**Comment by crisaless** [comment]
fixed and looking good!
